; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = printerMaster

[env:exposeWifi]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
src_filter = -<*> +<exposeWifi/>

[env:timeInBrowserExample]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
src_filter = -<*> +<timeInBrowserExample/>

[env:webServerBetterUI]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
board_build.filesystem = littlefs
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
src_filter = -<*> +<webServerBetterUI/>

[env:barcodeScanner]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
src_filter = -<*> +<barcodeScanner/>

[env:printerMaster]
platform = espressif32
board = lolin_c3_mini
; board = adafruit_feather_esp32s3
; board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
lib_deps = 
	h2zero/NimBLE-Arduino@^2.1.0
	adafruit/Adafruit GFX Library
   adafruit/Adafruit BusIO
	olikraus/U8g2@^2.33.6
	olikraus/U8g2_for_Adafruit_GFX
	ricmoo/QRCode
board_build.filesystem = littlefs
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
src_filter = -<*> +<printerMaster/>
